### PR TITLE
Add death print out functionality

### LINKED ISSUE #23: Enhance Match
Print out to the user when a Character is killed in the following format (Note the indentation of the death notices):

Release 2.0's sample run:

We have 5 survivors trying to make it to safety (0 children, 3 teachers, 2 soldiers)
But there are 9 zombies waiting for them (2 common infected, 7 tanks)
   Soldier 1 killed CommonInfected 0
   Soldier 1 killed CommonInfected 1
   Tank 2 killed Teacher 0
   Tank 2 killed Teacher 1
   Tank 2 killed Teacher 2
   Tank 4 killed Soldier 0
   Tank 4 killed Soldier 1
None of the survivors made it.

### PR DESCRIPTION
**Pull request by DBrueberg**
Added death print out functionality to PrintReportControl.java and altered Report.java to be able to display the correct Survivor Characters that are alive.

closes #23

### CODE REVIEW

**Review by noko12312 — APPROVED** [review]

**Review by flierc-csp — COMMENTED** [review]
I think this looks good, but should the ids be unique only to each class/character type?
_**Here is the example run:**_
```
Soldier 1 killed CommonInfected 0
Soldier 1 killed CommonInfected 1
Tank 2 killed Teacher 0
Tank 2 killed Teacher 1
Tank 2 killed Teacher 2
Tank 4 killed Soldier 0
Tank 4 killed Soldier 1
```

**Comment by DBrueberg** [comment]
@flierc-csp I believe they are unique, have I made an error? 

The algorithm is intended to work by assigning the index number as an id first 0 - n for Survivor, then 0 - n for Zombie. Then the index is held for each Character acting as a permanent ID until the Match is over.

**Review by flierc-csp — APPROVED** [review]

**Review by dietschc — APPROVED** [review]
Nicely done!

**Comment by DBrueberg** [comment]
Closed due to bug found by @flierc-csp . New Merge pull with changes opened as open #28

**Pull request closed without merging**
